Added get message by ID method with support for encrypted messages
DECENTfoundation/DCoreSwift-SDK pull request #54
Opened 2019-11-14 13:19 UTC by pepcox

…dded test for added functionality.

2019-11-14 14:50 UTC, lukas1 commented on Sources/DCoreKit/Api/MessagingApi.swift
> +     - Parameter byIds: Filter by message ids,
should be `ids` instead of `byIds`, to stay consistent with documentation for rest of methods

2019-11-14 14:50 UTC, lukas1 commented on Sources/DCoreKit/Api/MessagingApi.swift
> +     - Parameter byId: Filter by message id,
should be id instead of byId, to stay consistent with documentation for rest of methods

2019-11-14 14:50 UTC, lukas1 commented on Sources/DCoreKit/Api/MessagingApi.swift
> +     Get all messages by ids decrypted by sender.
Messages are not filtered by sender, this comment seems to be incorrect.

2019-11-14 14:50 UTC, lukas1 commented on Sources/DCoreKit/Api/MessagingApi.swift
> +     - Parameter byIds: Filter by message ids,
should be `ids`

2019-11-14 14:50 UTC, lukas1 commented on Sources/DCoreKit/Api/MessagingApi.swift
> +    func getAllDecrypted(_ credentials: Credentials, byIds ids: [ChainObjectConvertible]) -> Single<[Message]>
I think better method signature would be 
```Swift
func getAllDecrypted(byIds ids: [ChainObjectConvertible], credentials: Credentials) -> Single<[Message]>
```

2019-11-14 14:50 UTC, lukas1 commented on Sources/DCoreKit/Api/MessagingApi.swift
> +     Get message by id decrypted by sender.
messages are not filtered by sender

2019-11-14 14:50 UTC, lukas1 commented on Sources/DCoreKit/Api/MessagingApi.swift
> +     - Parameter byId: Filter by message id,
just `id`

2019-11-14 14:50 UTC, lukas1 commented on Sources/DCoreKit/Api/MessagingApi.swift
> +    func getDecrypted(_ credentials: Credentials, byId id: ChainObjectConvertible) -> Single<Message>
similar method signature as suggested for the `getAllDecrypted` method should be used

2019-11-14 14:50 UTC, lukas1 commented on Sources/DCoreKit/Net/Model/Request/GetMessages.swift
> +struct GetMessage: BaseRequestConvertible {
should be called `GetMessages`

2019-11-14 14:50 UTC, lukas1 commented on Sources/DCoreKit/Net/Model/Request/GetMessages.swift
> +        precondition(messages.allSatisfy { $0.objectType == .messagingObject }, "Not a valid message object id")
when ChainObject will be refactored so that it is split into particular sub-types, this precondition will not be necessary. I'm commenting here just to raise awareness of this piece of code later.

2019-11-14 14:50 UTC, lukas1 commented on Tests/DCoreKitTests/MessagingApiTests.swift
> +        XCTAssertNotNil(result)
this condition is not necessary. The below condition already captures the case of `result` being `nil`

2019-11-14 14:50 UTC, lukas1 commented on Tests/DCoreKitTests/MessagingApiTests.swift
> +        print("Noha ---- \(messageIds)")
pls remove this line

2019-11-14 14:50 UTC, lukas1 commented on Tests/DCoreKitTests/MessagingApiTests.swift
> +        XCTAssertNotNil(result)
this condition is not necessary

2019-11-14 14:50 UTC, lukas1 commented on Tests/DCoreKitTests/MessagingApiTests.swift
> +    func sendEncryptedMessage() -> String {
this change means that some places in code will probably throw a Swiftlint warning, or a compiler warning (about result of this method not being used). Best way to solve that warning is to take advantage of this annotation:
https://www.hackingwithswift.com/example-code/language/how-to-ignore-return-values-using-discardableresult

2019-11-14 14:50 UTC, lukas1 commented on Tests/DCoreKitTests/MessagingApiTests.swift
> +        ("testFindAllDecryptedMessagesBySenderUsingWrongCredentialsUsingWss", testFindAllDecryptedMessagesBySenderUsingWrongCredentialsUsingWss),
I think none of these methods actually need to have `usingWss` in their name. I know most of this code is old code, but now that I see it, I think it should be changed.

2019-11-15 08:05 UTC, pepcox commented on Sources/DCoreKit/Api/MessagingApi.swift
> +     Get all messages by ids decrypted by sender.
Messages are not filtered by sender but decrypted by sender Credentials.

2019-11-15 10:05 UTC, lukas1 commented on Sources/DCoreKit/Api/MessagingApi.swift
> +     Get all messages by ids decrypted by sender.
not necessarily sender credentials. Receiver can also decode a message ( as seen in `getAllReceiverDecrypted` )

2019-11-15 12:45 UTC, lukas1 approved these changes

2019-11-15 13:07 UTC, fl3xman requested changes

2019-11-15 13:07 UTC, fl3xman commented on Sources/DCoreKit/Api/MessagingApi.swift
> +    public func getAllDecrypted(byIds ids: [ChainObjectConvertible], _ credentials: Credentials) -> Single<[Message]> {
why we are hiding credentials?

2019-11-15 13:07 UTC, fl3xman commented on Sources/DCoreKit/Model/ProcessedTransaction.swift
> +    public let opResults: [[AnyValue]]?
pls leave this `AnyValue?` only and use if/case unwrap to get arrays.

2019-11-15 13:36 UTC, lukas1 commented on Sources/DCoreKit/Api/MessagingApi.swift
> +    public func getAllDecrypted(byIds ids: [ChainObjectConvertible], _ credentials: Credentials) -> Single<[Message]> {
ha, good point, didn't notice it, when I suggested changing method signature, credentials actually were not hidden in my suggestion. Pls remove `_`

2019-11-18 15:25 UTC, fl3xman commented on Sources/DCoreKit/Api/MessagingApi.swift
> +    func getAllDecrypted(byIds ids: [ChainObjectConvertible], _ credentials: Credentials) -> Single<[Message]>
do not hide credentials

2019-11-18 15:25 UTC, fl3xman commented on Sources/DCoreKit/Api/MessagingApi.swift
> +    func getDecrypted(byId id: ChainObjectConvertible, _ credentials: Credentials) -> Single<Message>
do not hide credentials

2019-11-19 09:07 UTC, lukas1 approved these changes

2019-11-19 09:07 UTC, lukas1 commented
pls resolve conflicts

2019-11-20 11:10 UTC, fl3xman approved these changes

2019-11-20 11:10 UTC, merged